---
- name: Install and use tree command with a cron job
  hosts: all
  become: yes
  tasks:
    - name: Install tree on Debian-based systems
      apt:
        name: tree
        state: present
      when: ansible_os_family == "Debian"

    - name: Install tree on RedHat-based systems
      yum:
        name: tree
        state: present
      when: ansible_os_family == "RedHat"

    - name: Ensure the output directory exists
      file:
        path: ~/anand/
        state: directory
        mode: '0755'

    - name: Ensure cron is installed on Debian-based systems
      apt:
        name: cron
        state: present
      when: ansible_os_family == "Debian"

    - name: Ensure cron is installed on RedHat-based systems
      yum:
        name: cronie
        state: present
      when: ansible_os_family == "RedHat"

    - name: Schedule a cron job to run tree command
      cron:
        name: "Run tree command daily"
        minute: "0"
        hour: "2"
        job: "tree ~/anand/ > ~/anand/tree_output.txt"

    - name: Display directory structure using tree
      command: cat ~/anand/tree_output.txt
      register: tree_output

    - name: Print tree output
      debug:
        var: tree_output.stdout
