---
- name: First basic playbook
  hosts: all
  tasks:
    - name: Test connectivity
      ping: {}

    - name: Install Apache (Debian-based)
      apt:
        name: apache2
        state: present
      when: ansible_os_family == "Debian"

    - name: Install Apache (Red Hat-based)
      yum:
        name: httpd
        state: present
      when: ansible_os_family == "RedHat"